spring:
  application:
    name: flood-map-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/flood_map_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  port: 8080

app:
  jwtSecret: floodMapHanoiSecretKeyWithAtLeast256BitsLongEnoughForHMACSHA256
  jwtExpirationMs: 86400000
